triggers:
  - envs: []
    last_enabled_at: 2024-02-06 09:36:19.096461
    name: daily_run
    pipeline_uuid: green_taxi_etl
    schedule_interval: "@daily"
    schedule_type: time
    settings: null
    sla: null
    start_time: 2024-02-06 05:00:00
    status: active
    variables: {}
